---
all:
  children:
    web:
      hosts:
        web01:
          ansible_host: 192.168.56.11
        web02:
          ansible_host: 192.168.56.12

    db:
      hosts:
        db01:
          ansible_host: 192.168.56.13
